#pragma once

#ifdef APIGEN_ACTIVE
#	define APIGEN_ANNOTATE(X) __attribute__((annotate(X)))
#else
#	define APIGEN_ANNOTATE(X)
#endif

#define APIGEN_STR_EXPAND(X) #X
#define APIGEN_STR(X) APIGEN_STR_EXPAND(X)


#define APIGEN_ANNOTATION_PREFIX         "apigen_"

#define APIGEN_ANNOTATION_EXPORT         APIGEN_ANNOTATION_PREFIX "export"
#define APIGEN_ANNOTATION_EXCLUDE        APIGEN_ANNOTATION_PREFIX "exclude"
#define APIGEN_ANNOTATION_RECURSIVE      APIGEN_ANNOTATION_PREFIX "recursive"

#define APIGEN_ANNOTATION_BASE           APIGEN_ANNOTATION_PREFIX "base"
#define APIGEN_ANNOTATION_NOBASE         APIGEN_ANNOTATION_PREFIX "nobase"
#define APIGEN_ANNOTATION_BASETREE       APIGEN_ANNOTATION_PREFIX "basetree"

#define APIGEN_ANNOTATION_RENAME         APIGEN_ANNOTATION_PREFIX "rename"
#define APIGEN_ANNOTATION_RENAME_PREFIX  APIGEN_ANNOTATION_RENAME ":"


#define APIGEN_API_CLASS_NAME _apigen_api_impls
class APIGEN_API_CLASS_NAME;
#define APIGEN_ENABLE_PRIVATE_EXPORT friend ::APIGEN_API_CLASS_NAME


#define APIGEN_EXPORT                    APIGEN_ANNOTATE(APIGEN_ANNOTATION_EXPORT)
#define APIGEN_EXCLUDE                   APIGEN_ANNOTATE(APIGEN_ANNOTATION_EXCLUDE)
#define APIGEN_EXPORT_RECURSIVE          APIGEN_EXPORT APIGEN_ANNOTATE(APIGEN_ANNOTATION_RECURSIVE)

#define APIGEN_EXPORT_BASE               APIGEN_EXPORT APIGEN_ANNOTATE(APIGEN_ANNOTATION_BASE)
#define APIGEN_NOBASE                    APIGEN_ANNOTATE(APIGEN_ANNOTATION_NOBASE)
#define ALIGEN_EXPORT_BASETREE           APIGEN_EXPORT_BASE APIGEN_ANNOTATE(APIGEN_ANNOTATION_BASETREE)

#define APIGEN_RENAME(NAME)              APIGEN_ANNOTATE(APIGEN_ANNOTATION_RENAME_PREFIX APIGEN_STR(NAME))
