#pragma once

#ifdef APIGEN_ACTIVE
#	define APIGEN_ANNOTATE(X) __attribute__((annotate(X)))
#else
#	define APIGEN_ANNOTATE(X)
#endif

#define APIGEN_STR_EXPAND(X) #X
#define APIGEN_STR(X) APIGEN_STR_EXPAND(X)

#define APIGEN_ANNOTATION_EXPORT "apigen_export"
#define APIGEN_ANNOTATION_EXCLUDE "apigen_exclude"
#define APIGEN_ANNOTATION_RECURSIVE "apigen_recursive"
#define APIGEN_ANNOTATION_BASE "apigen_base"
#define APIGEN_ANNOTATION_RENAME "apigen_rename"
#define APIGEN_ANNOTATION_RENAME_PREFIX APIGEN_ANNOTATION_RENAME ":"

#define APIGEN_EXPORT APIGEN_ANNOTATE(APIGEN_ANNOTATION_EXPORT)
#define APIGEN_EXCLUDE APIGEN_ANNOTATE(APIGEN_ANNOTATION_EXCLUDE)
#define APIGEN_EXPORT_RECURSIVE APIGEN_EXPORT APIGEN_ANNOTATE(APIGEN_ANNOTATION_RECURSIVE)
#define APIGEN_EXPORT_BASE APIGEN_EXPORT APIGEN_ANNOTATE(APIGEN_ANNOTATION_BASE)
#define APIGEN_RENAME(NAME) APIGEN_ANNOTATE(APIGEN_ANNOTATION_RENAME_PREFIX APIGEN_STR(NAME))
